version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    commands:
      - yarn
      - npm install next -g
  build:
    commands:
      - npx next build
artifacts:
  files:
    - '**/*'